[package]
name = "rosrust_codegen"
version = "0.9.6"
edition = "2024"

[features]
derive-serde = ["rosrust_codegen_inner/derive-serde", "serde", "serde/derive"]

[dependencies.rosrust_codegen_inner]
path = "../rosrust_codegen_inner"
version = "0.9.6"

[dependencies.serde]
version = "1"
optional = true

[lib]
proc-macro = true
